import { chromium } from "playwright";
import { mkdir } from "node:fs/promises";
const output = "test-results/redesign-states";
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 320, height: 568 }, reducedMotion: "reduce" });
await page.goto("http://localhost:3000/forecast");
await page.locator("button.filter-chip").first().click();
await page.getByRole("dialog").waitFor({ state: "visible" });
await page.screenshot({ path: output + "/forecast-filters-320.png" });
await page.setViewportSize({ width: 320, height: 340 });
await page.getByRole("dialog").getByLabel("Localita").focus();
await page.getByRole("button", { name: "Mostra previsioni" }).scrollIntoViewIfNeeded();
const footer = await page.getByRole("button", { name: "Mostra previsioni" }).boundingBox();
if (!footer || footer.y < 0 || footer.y + footer.height > 340) throw new Error("Sheet footer clipped by the keyboard viewport");
await page.screenshot({ path: output + "/forecast-keyboard-320.png" });
await page.keyboard.press("Escape");
await page.setViewportSize({ width: 390, height: 844 });
await page.goto("http://localhost:3000/map");
await page.locator(".spot-marker").first().waitFor({ timeout: 25000 });
let release;
const pause = new Promise(resolve => { release = resolve; });
await page.route("**/api/forecast?**", async route => { await pause; await route.continue(); });
await page.locator(".spot-list").getByRole("button", { name: /Scogliera nord/ }).click();
await page.locator(".spot-details .skeleton").waitFor({ state: "visible" });
await page.screenshot({ path: output + "/spot-loading-390.png" });
release();
await page.locator(".spot-details .skeleton").waitFor({ state: "hidden" });
await page.screenshot({ path: output + "/spot-details-390.png" });
await page.getByRole("button", { name: "Espandi pannello spot" }).click();
await page.screenshot({ path: output + "/spot-expanded-390.png" });
await page.goto("http://localhost:3000/sessions");
await page.getByRole("button", { name: "Filtri" }).click();
await page.getByRole("dialog").getByLabel("Disciplina").selectOption("BOAT");
await page.getByRole("button", { name: "Mostra uscite" }).click();
await page.screenshot({ path: output + "/journal-empty-390.png" });
console.log("Verified filter sheet, reduced keyboard viewport, spot loading/details/expanded and empty journal.");
await browser.close();
